/**
 * Better Auth API Routes
 * ======================
 * This catch-all route handler manages all authentication endpoints.
 * Routes are automatically generated by better-auth at /api/auth/*
 */

import { auth } from "@/lib/auth";
import { toNextJsHandler } from "better-auth/next-js";

export const { GET, POST } = toNextJsHandler(auth);
